### ISSUE TITLE
Add Additional Login Methods Using Firebase Authentication (Minimum 3 Providers)

### ISSUE THREAD

**Issue by amri-tah** [amri-tah/LeetPath#4]
**Description**  
The LeetPath website currently supports limited login options (Email and Google). To improve user convenience and accessibility, we need to integrate additional login methods such as Facebook, GitHub, and others using Firebase Authentication.  

#### Requirements  
1. **Integrate Additional Providers**  
   - Add support for the following login methods using Firebase:  
     - Facebook  
     - GitHub, wtc

2. **Update Firebase Configuration**  
   - Enable the selected providers in the Firebase console.  
   - Update the Firebase configuration in the project to include the necessary API keys and secrets.  

3. **Frontend Changes**  
   - Add buttons or icons for the new login methods on the login page.  
   - Style the buttons to maintain consistency with the website's design.  

#### Acceptance Criteria  
- Users can log in using other sign in methods seamlessly.  
- The login page UI clearly displays the new options.  

- Ensure that the OAuth credentials (API keys, secrets) are stored securely and not exposed in the codebase.

**Comment by eshwanthkartitr** [comment]
Hi @amri-tah i would like to contribute to this work

**Comment by VishalTheHuman** [comment]
Hey @eshwanthkartitr! Noticed that you've already been assigned issues under more than two other repositories. Please complete those and raise PRs before requesting this issue. Excited to see your contributions!

**Comment by JrGkOG** [comment]
Hi @VishalTheHuman I would like to take up this task of integrating Facebook and GitHub login options using Firebase Authentication.

**Comment by VishalTheHuman** [comment]
Hey @adofm , you've been assigned this issue under Amrita Winter of Code! Please ensure to raise a PR by 39/12/2024, or it will be reassigned to someone else. Best of luck! 🫡

**Comment by VishalTheHuman** [comment]
> Hi @VishalTheHuman I would like to take up this task of integrating Facebook and GitHub login options using Firebase Authentication.

Facebook, Microsoft, Github. Message me personally to get the firebase key and access.

**Comment by JrGkOG** [comment]
Sure.

**Comment by adithya-menon-r** [comment]
Hey @VishalTheHuman, I would like to solve this issue if there is no progress.

**Comment by VishalTheHuman** [comment]
@adofm Great Work. Bounty will be added soon.

**Comment by JrGkOG** [comment]
> @adofm Great Work. Bounty will be added soon.

Thanks it was great working with you.
